name: mimicon
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_mlkit_face_detection: ^0.9.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  camera: ^0.10.5+9
  image_gallery_saver: ^2.0.3
  another_flushbar: ^1.12.30

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/